"""Facade for the IPA domain."""

from .ssr import (
    add_ipa_course_to_planificacion,
    build_ipa_add_course_url,
    build_ipa_course_progress_payload,
    build_ipa_massive_planificaciones_url,
    build_ipa_result_excel_bytes,
    build_ipa_result_filename,
    build_ipa_result_json_bytes,
    build_ipa_result_payload,
    build_ipa_result_rows,
    build_ipa_school_courses_payload,
    build_ipa_schools_payload,
    extract_ipa_session_value,
    fetch_ipa_add_course_context,
    fetch_ipa_course_progress,
    fetch_ipa_grade_areas,
    fetch_ipa_grade_listing,
    fetch_ipa_massive_planificaciones,
    fetch_ipa_school_courses,
    fetch_ipa_schools_listing,
    fetch_ipa_structure,
    search_ipa_course_for_planificacion,
)
from .view import render_ipa_view

__all__ = [
    "add_ipa_course_to_planificacion",
    "build_ipa_add_course_url",
    "build_ipa_course_progress_payload",
    "build_ipa_massive_planificaciones_url",
    "build_ipa_result_excel_bytes",
    "build_ipa_result_filename",
    "build_ipa_result_json_bytes",
    "build_ipa_result_payload",
    "build_ipa_result_rows",
    "build_ipa_school_courses_payload",
    "build_ipa_schools_payload",
    "extract_ipa_session_value",
    "fetch_ipa_add_course_context",
    "fetch_ipa_course_progress",
    "fetch_ipa_grade_areas",
    "fetch_ipa_grade_listing",
    "fetch_ipa_massive_planificaciones",
    "fetch_ipa_school_courses",
    "fetch_ipa_schools_listing",
    "fetch_ipa_structure",
    "search_ipa_course_for_planificacion",
    "render_ipa_view",
]
